/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class qpnativecrypt */

#ifndef _Included_qpnativecrypt
#define _Included_qpnativecrypt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     qpnativecrypt
 * Method:    testWord
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_qpnativecrypt_testWord
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
