/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class qpnativejcrypt */

#ifndef _Included_qpnativejcrypt
#define _Included_qpnativejcrypt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     qpnativejcrypt
 * Method:    testWord
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_qpnativejcrypt_testWord
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
