/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class qpnativeaes */

#ifndef _Included_qpnativeaes
#define _Included_qpnativeaes
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     qpnativeaes
 * Method:    testWord
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_qpnativeaes_testWord
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
