/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class qpnativeblowfish */

#ifndef _Included_qpnativeblowfish
#define _Included_qpnativeblowfish
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     qpnativeblowfish
 * Method:    testWord
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_qpnativeblowfish_testWord
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
