/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class qpnativerijndael */

#ifndef _Included_qpnativerijndael
#define _Included_qpnativerijndael
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     qpnativerijndael
 * Method:    testWord
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_qpnativerijndael_testWord
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
